### PR TITLE
chore: remove precompiled binaries

### PR DESCRIPTION
**Pull request by bobbyg603**
Use Neon to call into the Mozilla dump_syms crate. This is a barebones implementation for now and we can follow up with support for additional options.

### TODO
- [x] Reintroduce install script
- [x] Fork node-pre-gyp-github and set the branch to main following this example https://github.com/bchr02/node-pre-gyp-github/issues/45

BREAKING CHANGE: replace dumpSyms and dumpSymsSync with single dumpSyms that calls the native addon.

### CODE REVIEW

**Comment by bobbyg603** [comment]
TODO BG re-add the install script. The addon has to be compiled for the target platform.

**Comment by bobbyg603** [comment]
> TODO BG re-add the install script. The addon has to be compiled for the target platform.

try to build the rust binary, log a warning if we don't, log a warning if we can't load them

**Comment by bobbyg603** [comment]
Interesting example https://github.com/amilajack/node-disk-utility/blob/master/package.json

**Comment by bobbyg603** [comment]
https://github.com/bchr02/node-pre-gyp-github/issues/45

**Review by daveplunkett — APPROVED** [review]

**Pull request merged**
